name: agenperubahan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  sliding_up_panel: ^1.0.2
  video_player: ^1.0.1
  chewie: 
  


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/fajar.jpg
    - assets/video.mp4
    - assets/images/background.jpg
    - assets/
    - assets/images/gedungkotak1.png
    - assets/images/gedungkotak2.png
    - assets/images/gedungkotak3.png
    - assets/images/gedungkotak4.png
    - assets/images/gedungkotak5.png
    - assets/images/gedungkotak6.png
    - assets/images/gedungkotak7.png
    - assets/images/gedungkotak8.png
    - assets/images/gedungoval1.png
    - assets/images/gedungoval2.png
    - assets/images/gedungoval3.png
    - assets/images/gedungoval4.png
    - assets/images/gedungoval5.png
    - assets/images/gedungoval6.png

    - assets/images/gedungoval8.png
    - assets/images/gedungoval9.png
    - assets/images/gedungoval10.png
    - assets/images/gedungoval11.png
    - assets/images/gedungoval12.png
    - assets/images/gedungoval13.png
    - assets/images/gedungpaud1.png
    - assets/images/gedungpaud2.png
    - assets/images/gedungpaud3.png
    - assets/images/gedungpaud4.png

    - assets/images/kampungkerajinan1.png
    - assets/images/kampungkerajinan2.png
    - assets/images/kampungkerajinan3.png
    - assets/images/kampungkerajinan4.png
    - assets/images/kampungkerajinan5.png
    - assets/images/kampungkerajinan6.png
    - assets/images/kampungkerajinan7.png
    - assets/images/kampungkerajinan8.png
    - assets/images/kampungkerajinan9.png
    - assets/images/planetarium1.png
    - assets/images/planetarium2.png
    - assets/images/playground1.png
    - assets/images/playground2.png
    - assets/images/playground3.png
    - assets/images/playground4.png
    - assets/images/playground5.png
    - assets/images/playground6.png
    - assets/images/playground7.png
    - assets/images/playground8.png
    - assets/images/sciencetheater1.png
    - assets/images/sciencetheater2.png
    - assets/images/wahanabahari1.png
    - assets/images/wahanabahari2.png
    - assets/images/zonaperpus1.png
    - assets/images/zonaperpus2.png

   
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
